package com.pg2dev;

import com.pg2dev.model.Block;
import com.pg2dev.model.Wallet;
import java.awt.event.KeyEvent;
import java.security.Security;
import java.util.ArrayList;

/**
 *
 * @author Patricio Iván Garcia Zitarosa <patriciogarcia1988@gmail.com>
 */
public class JFrame extends javax.swing.JFrame implements Node.IListener {

    private StringBuilder logs;
    private Node node;
    private Wallet sender;
    private Wallet recipient;

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
        logs = new StringBuilder();
        Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider());
        this.setup();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        senderBalance = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textLog = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        recipientBalance = new javax.swing.JLabel();
        jTextFieldAmount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonTransfer = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonPrintBlockchain = new javax.swing.JButton();
        jButtonWrongBlock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        senderBalance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Saldo Origen:");

        textLog.setEditable(false);
        textLog.setColumns(20);
        textLog.setRows(5);
        jScrollPane1.setViewportView(textLog);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Saldo Destino:");

        recipientBalance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextFieldAmount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldAmount.setText("100");
        jTextFieldAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAmountKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Monto");

        jButtonTransfer.setText("Transferir");
        jButtonTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransferActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonPrintBlockchain.setText("Impirmir blockchain");
        jButtonPrintBlockchain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintBlockchainActionPerformed(evt);
            }
        });

        jButtonWrongBlock.setText("Bloque erröneo");
        jButtonWrongBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWrongBlockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(senderBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(recipientBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 245, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTransfer)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonWrongBlock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPrintBlockchain)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReset)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(senderBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(recipientBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTransfer)
                    .addComponent(jButtonReset)
                    .addComponent(jButtonPrintBlockchain)
                    .addComponent(jButtonWrongBlock))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAmountKeyTyped
        char character = evt.getKeyChar();
        if (!(Character.isDigit(character) || (character == KeyEvent.VK_BACK_SPACE) || (character == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldAmountKeyTyped

    private void jButtonTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransferActionPerformed
        float value = Float.valueOf(jTextFieldAmount.getText());
        node.send(value);
    }//GEN-LAST:event_jButtonTransferActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        this.log("Restarting values...");
        this.setup();
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonPrintBlockchainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintBlockchainActionPerformed
        ArrayList<Block> blockchain = node.getBlockchain();
        for (Block block : blockchain) {
            this.log(block.toString());
        }
        this.log("---------------------------------------------");
    }//GEN-LAST:event_jButtonPrintBlockchainActionPerformed

    private void jButtonWrongBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWrongBlockActionPerformed
        float value = Float.valueOf(jTextFieldAmount.getText());
        node.addWrongBLock(value);
    }//GEN-LAST:event_jButtonWrongBlockActionPerformed

    @Override
    public void onSenderBalanceChange(float value) {
        senderBalance.setText(Float.toString(value));
    }

    @Override
    public void onrecipientBalanceChange(float value) {
        recipientBalance.setText(Float.toString(value));
    }

    @Override
    public void log(String str) {
        logs.append(str).append('\n');
        textLog.setText(logs.toString());
    }

    private void setup() {
        node = new Node(this);

        Wallet wallet = new Wallet();
        node.setBaseWallet(wallet);

        sender = new Wallet();
        recipient = new Wallet();

        sender.getPublicKey();

        node.setSender(sender);
        node.setRecipient(recipient);

        node.initialize(5000);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                javax.swing.UIManager.setLookAndFeel(lookAndFeel);
            } catch (Exception ex) {
                new RuntimeException(ex);
            }
            new JFrame().setVisible(true);
        });
    }
    private static final String lookAndFeel = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPrintBlockchain;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonTransfer;
    private javax.swing.JButton jButtonWrongBlock;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JLabel recipientBalance;
    private javax.swing.JLabel senderBalance;
    private javax.swing.JTextArea textLog;
    // End of variables declaration//GEN-END:variables
}
